# Comprehensive lint rules from Very Good Ventures
# https://pub.dev/packages/very_good_analysis
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Disabled: requiring docs on all public APIs is excessive for applications
    public_member_api_docs: false
